site_name: Mathium05's blog
site_description: A blog of Mathium05's various projects, including Fermi
site_url: https://blog.fermi.chat
repo_url: https://github.com/MathMan05/Fermi
theme:
  name: material
  favicon: logo.webp
  custom_dir: overrides
  features:
    - navigation.indexes
  palette:
  # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode



plugins:
  - search
  - blog:
      blog_toc: true
      archive_date_format: MMMM yyyy
      categories_allowed:
        - Meta
        - Fermi
      authors_profiles: true
      pagination_per_page: 5
      archive_pagination_per_page: 10
      categories_pagination_per_page: 10
  - meta
  - tags
  - rss:
      match_path: "blog/posts/.*"
      use_git: false
      date_from_meta:
        as_creation: date.created
        as_update: date.updated

extra:
  social:
    - icon: fontawesome/brands/discord
      name: Spacebar Discord server
      link: https://discord.gg/JDjMXTGeY9
    - icon: fontawesome/brands/github
      name: Mathium05's github
      link: https://github.com/MathMan05

hooks:
  - hooks/socialmedia.py

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Blog:
     - blog/index.md
     - blog/tags.md
