name: IndexNow Action
on: [push]

jobs:
  indexnow:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for 3 minutes
        run: sleep 180

      - name: IndexNow Action
        uses: bojieyang/indexnow-action@v2
        with:
          sitemap-location: 'https://blog.fermi.chat/sitemap.xml'
          key: ${{ secrets.INDEXNOW_KEY }}
